apiVersion: v1
kind: Service
metadata:
  name: todo-devops-service
spec:
  selector:
    app: todo-devops
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080
  type: LoadBalancer